name: Generate Profile Summary Cards

on:
  schedule:
    # Runs once a day at 00:45 UTC
    - cron: "45 0 * * *"
  workflow_dispatch: # allow manual runs from the Actions tab
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
